package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatAddress;

public interface EatAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_address
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int deleteByPrimaryKey(Long addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_address
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_address
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insertSelective(EatAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_address
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatAddress selectByPrimaryKey(Long addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_address
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKeySelective(EatAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_address
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(EatAddress record);
}