package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatCuisine;

public interface EatCuisineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_cuisine
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */

    int deleteByPrimaryKey(Long cuisineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_cuisine
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatCuisine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_cuisine
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insertSelective(EatCuisine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_cuisine
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatCuisine selectByPrimaryKey(Long cuisineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_cuisine
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKeySelective(EatCuisine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_cuisine
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(EatCuisine record);
}