package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatComment;

public interface EatCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_comment
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int deleteByPrimaryKey(Long commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_comment
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_comment
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insertSelective(EatComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_comment
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatComment selectByPrimaryKey(Long commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_comment
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKeySelective(EatComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_comment
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(EatComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_comment
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(EatComment record);
}