package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatComment;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EatCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_comment
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int deleteByPrimaryKey(Long commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_comment
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_comment
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insertSelective(EatComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_comment
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatComment selectByPrimaryKey(Long commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_comment
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKeySelective(EatComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_comment
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(EatComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_comment
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(EatComment record);

    /**
     * 后台查询全部评论
     * @姚天祥 set 2020-02-28 09:00
     */
    List<EatComment> selectAll();
    /**
     * 后台添加评论
     * @姚天祥 set 2020-02-28 09:00
     */
    int addComment(EatComment eatComment);

    /**
     * 后台根据ID查询评论
     * @姚天祥 set 2020-02-28 10:00
     */
    EatComment findComById(@Param("commentId")Integer commentId);
    /**
     * 修改评论
     * @姚天祥 set 2020-02-28 10:00
     */
    int updateComment(EatComment eatComment);

    /**
     * 根据ID删除评论信息
     * @姚天祥 set 2020-02-28 11:00
     */
    int deleteById(@Param("commentId")Integer commentId);

}