package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatGreens;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EatGreensMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_greens
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int deleteByPrimaryKey(Long greensId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_greens
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatGreens record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_greens
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insertSelective(EatGreens record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_greens
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatGreens selectByPrimaryKey(Long greensId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_greens
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKeySelective(EatGreens record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_greens
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(EatGreens record);

    /**
     * 添加菜品信息
     * @姚天祥 set 2020-02-26 09:00
     *
     */
    int addGreens(EatGreens eatGreens);

    /**
     * 删除菜品信息
     * @姚天祥 set 2020-02-27 09:00
     */
    int deleteById(@Param("greensId")Integer greensId);

    /**
     * 查询所有菜品
     * @姚天祥 set 2020-02-27 10:00
     */
    List<EatGreens> selectAll(@Param("greensName")String greensName);

    /**
     * 查看菜品详情
     * @姚天祥 set 2020-02-27 11:00
     */
    EatGreens findGreensById(@Param("greensId")String greensId);
    /**
     * 修改菜品详情
     * @姚天祥 set 2020-02-27 11:00
     */
    int updateGreensById(EatGreens eatGreens);
}