package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatGreens;

public interface EatGreensMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_greens
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int deleteByPrimaryKey(Long greensId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_greens
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatGreens record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_greens
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insertSelective(EatGreens record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_greens
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatGreens selectByPrimaryKey(Long greensId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_greens
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKeySelective(EatGreens record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_greens
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(EatGreens record);
}