package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatHorseman;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EatHorsemanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_horseman
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int deleteByPrimaryKey(String horsemanPhone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_horseman
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatHorseman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_horseman
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insertSelective(EatHorseman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_horseman
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatHorseman selectByPrimaryKey(String horsemanPhone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_horseman
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKeySelective(EatHorseman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_horseman
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(@Param("horsemanPhone")String horsemanPhone);

    /**
     * 后台增加骑手接口
     * @姚天祥 set 2020-02-22 23:00:00
     */
    int addHoresman(EatHorseman horseman);

    /**
     * 后台根据姓名或电话分页查询骑手接口
     * @姚天祥 set 2020-02-23 08:30
     */
    List<EatHorseman> selectHoresmanByNameOrPhone(@Param("horsemanName")String horsemanName,@Param("horsemanPhone")String horsemanPhone);

    /**
     * 进入后台显示骑手列表接口
     * @姚天祥 set 2020-02-23 08:40
     */
    List<EatHorseman> selectHoresmanAll();

    /**
     * 后台根据骑手电话修改骑手信息
     * @姚天祥 set 2020-02-23 16:30
     */
    int updateByPhone(@Param("horsemanName")String horsemanName);

}