package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatHorseman;

public interface EatHorsemanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_horseman
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int deleteByPrimaryKey(String horsemanPhone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_horseman
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatHorseman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_horseman
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insertSelective(EatHorseman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_horseman
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatHorseman selectByPrimaryKey(String horsemanPhone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_horseman
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKeySelective(EatHorseman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_horseman
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(EatHorseman record);
}