package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatMerchant;

public interface EatMerchantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_merchant
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int deleteByPrimaryKey(Integer merchantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_merchant
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_merchant
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insertSelective(EatMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_merchant
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatMerchant selectByPrimaryKey(Integer merchantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_merchant
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKeySelective(EatMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_merchant
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(EatMerchant record);
}