package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatOrder;

public interface EatOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_order
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_order
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_order
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insertSelective(EatOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_order
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_order
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKeySelective(EatOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_order
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(EatOrder record);
}