package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatStatus;

public interface EatStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_status
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int deleteByPrimaryKey(Integer statusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_status
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_status
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insertSelective(EatStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_status
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatStatus selectByPrimaryKey(Integer statusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_status
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKeySelective(EatStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_status
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(EatStatus record);
}