package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatShopping;

public interface EatShoppingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_shopping
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int deleteByPrimaryKey(Long shoppingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_shopping
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatShopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_shopping
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insertSelective(EatShopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_shopping
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatShopping selectByPrimaryKey(Long shoppingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_shopping
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKeySelective(EatShopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_shopping
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(EatShopping record);
}