package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EatUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insertSelective(EatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKeySelective(EatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(EatUser record);


    /**
     * 添加用户方法
     * @param user
     * @return
     */
    int addUser(EatUser user);

    /**
     * 删除用户方法
     * @param id
     * @return
     */
    int deleteUser(@Param("id")Integer id);


    /**
     * 根据用户id查询用户信息
     * @param id
     * @return
     */
    EatUser selectUserById(@Param("id") Integer id);

    /**
     * 修改用户方法
     * @param user
     * @return
     */
    int updateUser(EatUser user);


    /**
     * 根据商家地址查询
     * @param address
     * @return
     */
    List<EatUser> selectByAddress(String address);

    /**
     * 根据菜品名称查询
     * @param greensName
     * @return
     */
    List<EatUser> selectByGreens(String greensName);





}