package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatUser;
import org.apache.ibatis.annotations.Param;

public interface EatUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insertSelective(EatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKeySelective(EatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(EatUser record);

    /**
     * 前台骑手电话查看用户信息
     * @姚天祥 set 2020-02-25 11:00
     */
    EatUser findUserByPhone (@Param("userPhone")String userPhone);
}