package cn.kgc.eat.mapper;

import cn.kgc.eat.pojo.EatUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EatUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    /**
     * @author 齐宏伟
     * @desc 管理员删除用户信息
     * @date 2020/2/23
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int insert(EatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    /**
     * @author 齐宏伟
     * @desc 管理员增加用户信息
     * @date 2020/2/23
     */
    int insertSelective(EatUser eatUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    EatUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    /**
     * @author 齐宏伟
     * @desc 管理员修改用户信息
     * @date 2020/2/23
     */
    int updateByPrimaryKeySelective(EatUser eatUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eat_user
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    int updateByPrimaryKey(EatUser record);

    /**
     * @author 齐宏伟
     * @desc 管理员查询用户信息
     * @date 2020/2/23
     */
    public List<EatUser> getUserList();
    /**
     * @author 齐宏伟
     * @desc 根据用户id查询用户信息
     * @date 2020/2/23
     */
    public EatUser getUserById(String USER_ID);
}