package cn.kgc.eat.pojo;

public class EatAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_address.ADDRESS_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Long addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_address.ADDRESS_USER_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Integer addressUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_address.ADDRESS_USER_PHONE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String addressUserPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_address.ADDRESS_USER_ADDRESS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String addressUserAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_address.ADDRESS_ID
     *
     * @return the value of eat_address.ADDRESS_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_address.ADDRESS_ID
     *
     * @param addressId the value for eat_address.ADDRESS_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_address.ADDRESS_USER_ID
     *
     * @return the value of eat_address.ADDRESS_USER_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Integer getAddressUserId() {
        return addressUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_address.ADDRESS_USER_ID
     *
     * @param addressUserId the value for eat_address.ADDRESS_USER_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setAddressUserId(Integer addressUserId) {
        this.addressUserId = addressUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_address.ADDRESS_USER_PHONE
     *
     * @return the value of eat_address.ADDRESS_USER_PHONE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getAddressUserPhone() {
        return addressUserPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_address.ADDRESS_USER_PHONE
     *
     * @param addressUserPhone the value for eat_address.ADDRESS_USER_PHONE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setAddressUserPhone(String addressUserPhone) {
        this.addressUserPhone = addressUserPhone == null ? null : addressUserPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_address.ADDRESS_USER_ADDRESS
     *
     * @return the value of eat_address.ADDRESS_USER_ADDRESS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getAddressUserAddress() {
        return addressUserAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_address.ADDRESS_USER_ADDRESS
     *
     * @param addressUserAddress the value for eat_address.ADDRESS_USER_ADDRESS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setAddressUserAddress(String addressUserAddress) {
        this.addressUserAddress = addressUserAddress == null ? null : addressUserAddress.trim();
    }
}