package cn.kgc.eat.pojo;

import java.util.Date;

public class EatComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_comment.COMMENT_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Integer commentId;

    private  Integer commentMerchantId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_comment.COMMENT_AUTHOR
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Integer commentAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_comment.COMMENT_DATE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Date commentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_comment.COMMENT_CONTENT
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String commentContent;

    /**
     * 评论用户名称
     */
    private String commentUserName;

    public  EatComment(){}

    public EatComment(Integer commentMerchantId, Integer commentAuthor, Date commentDate, String commentContent) {
        this.commentMerchantId = commentMerchantId;
        this.commentAuthor = commentAuthor;
        this.commentDate = commentDate;
        this.commentContent = commentContent;
    }

    public Integer getCommentId() {
        return commentId;
    }

    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    public Integer getCommentMerchantId() {
        return commentMerchantId;
    }

    public void setCommentMerchantId(Integer commentMerchantId) {
        this.commentMerchantId = commentMerchantId;
    }

    public Integer getCommentAuthor() {
        return commentAuthor;
    }

    public void setCommentAuthor(Integer commentAuthor) {
        this.commentAuthor = commentAuthor;
    }

    public Date getCommentDate() {
        return commentDate;
    }

    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }

    public String getCommentContent() {
        return commentContent;
    }

    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }

    public String getCommentUserName() {
        return commentUserName;
    }

    public void setCommentUserName(String commentUserName) {
        this.commentUserName = commentUserName;
    }
}