package cn.kgc.eat.pojo;

public class EatCuisine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_cuisine.CUISINE_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Long cuisineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_cuisine.CUISINE_NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String cuisineName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_cuisine.CUISINE_ID
     *
     * @return the value of eat_cuisine.CUISINE_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Long getCuisineId() {
        return cuisineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_cuisine.CUISINE_ID
     *
     * @param cuisineId the value for eat_cuisine.CUISINE_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setCuisineId(Long cuisineId) {
        this.cuisineId = cuisineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_cuisine.CUISINE_NAME
     *
     * @return the value of eat_cuisine.CUISINE_NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getCuisineName() {
        return cuisineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_cuisine.CUISINE_NAME
     *
     * @param cuisineName the value for eat_cuisine.CUISINE_NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setCuisineName(String cuisineName) {
        this.cuisineName = cuisineName == null ? null : cuisineName.trim();
    }
}