package cn.kgc.eat.pojo;

import java.util.Date;

public class EatComment {

    /**
     * 商家id
     */
    private  Integer commentMerchantId; /**
     * 评论用户名称
     */
    private String commentUserName;

    public Integer getCommentMerchantId() {
        return commentMerchantId;
    }

    public void setCommentMerchantId(Integer commentMerchantId) {
        this.commentMerchantId = commentMerchantId;
    }

    public String getCommentUserName() {
        return commentUserName;
    }

    public void setCommentUserName(String commentUserName) {
        this.commentUserName = commentUserName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_comment.COMMENT_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Long commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_comment.COMMENT_AUTHOR
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Integer commentAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_comment.COMMENT_DATE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Date commentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_comment.COMMENT_CONTENT
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String commentContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_comment.COMMENT_ID
     *
     * @return the value of eat_comment.COMMENT_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_comment.COMMENT_ID
     *
     * @param commentId the value for eat_comment.COMMENT_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_comment.COMMENT_AUTHOR
     *
     * @return the value of eat_comment.COMMENT_AUTHOR
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Integer getCommentAuthor() {
        return commentAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_comment.COMMENT_AUTHOR
     *
     * @param commentAuthor the value for eat_comment.COMMENT_AUTHOR
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setCommentAuthor(Integer commentAuthor) {
        this.commentAuthor = commentAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_comment.COMMENT_DATE
     *
     * @return the value of eat_comment.COMMENT_DATE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Date getCommentDate() {
        return commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_comment.COMMENT_DATE
     *
     * @param commentDate the value for eat_comment.COMMENT_DATE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_comment.COMMENT_CONTENT
     *
     * @return the value of eat_comment.COMMENT_CONTENT
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_comment.COMMENT_CONTENT
     *
     * @param commentContent the value for eat_comment.COMMENT_CONTENT
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }
}