package cn.kgc.eat.pojo;

import com.alibaba.fastjson.annotation.JSONField;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class EatHorseman {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_horseman.HORSEMAN_PHONE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String horsemanPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_horseman.HORSEMAN_NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String horsemanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_horseman.HORSEMAN_PASSWORD
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String horsemanPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_horseman.HORSEMAN_BORN_DATE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JSONField(format = "yyyy-MM-dd")
    private Date horsemanBornDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_horseman.HORSEMAN_ADDRESS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String horsemanAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_horseman.HORSEMAN_PHONE
     *
     * @return the value of eat_horseman.HORSEMAN_PHONE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getHorsemanPhone() {
        return horsemanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_horseman.HORSEMAN_PHONE
     *
     * @param horsemanPhone the value for eat_horseman.HORSEMAN_PHONE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setHorsemanPhone(String horsemanPhone) {
        this.horsemanPhone = horsemanPhone == null ? null : horsemanPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_horseman.HORSEMAN_NAME
     *
     * @return the value of eat_horseman.HORSEMAN_NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getHorsemanName() {
        return horsemanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_horseman.HORSEMAN_NAME
     *
     * @param horsemanName the value for eat_horseman.HORSEMAN_NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setHorsemanName(String horsemanName) {
        this.horsemanName = horsemanName == null ? null : horsemanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_horseman.HORSEMAN_PASSWORD
     *
     * @return the value of eat_horseman.HORSEMAN_PASSWORD
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getHorsemanPassword() {
        return horsemanPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_horseman.HORSEMAN_PASSWORD
     *
     * @param horsemanPassword the value for eat_horseman.HORSEMAN_PASSWORD
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setHorsemanPassword(String horsemanPassword) {
        this.horsemanPassword = horsemanPassword == null ? null : horsemanPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_horseman.HORSEMAN_BORN_DATE
     *
     * @return the value of eat_horseman.HORSEMAN_BORN_DATE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Date getHorsemanBornDate() {
        return horsemanBornDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_horseman.HORSEMAN_BORN_DATE
     *
     * @param horsemanBornDate the value for eat_horseman.HORSEMAN_BORN_DATE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setHorsemanBornDate(Date horsemanBornDate) {
        this.horsemanBornDate = horsemanBornDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_horseman.HORSEMAN_ADDRESS
     *
     * @return the value of eat_horseman.HORSEMAN_ADDRESS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getHorsemanAddress() {
        return horsemanAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_horseman.HORSEMAN_ADDRESS
     *
     * @param horsemanAddress the value for eat_horseman.HORSEMAN_ADDRESS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setHorsemanAddress(String horsemanAddress) {
        this.horsemanAddress = horsemanAddress == null ? null : horsemanAddress.trim();
    }
}