package cn.kgc.eat.pojo;

public class EatMerchant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_merchant.MERCHANT_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_merchant.MERCHANT_PHONE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String merchantPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_merchant.MERCHANT_ADDRESS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String merchantAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_merchant.MERCHANT_STATUS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String merchantStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_merchant.MERCHANT_EMAIL
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String merchantEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_merchant.MERCHANT_NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_merchant.MERCHANT_SECURITY_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Integer merchantSecurityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_merchant.MERCHANT_ID
     *
     * @return the value of eat_merchant.MERCHANT_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_merchant.MERCHANT_ID
     *
     * @param merchantId the value for eat_merchant.MERCHANT_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_merchant.MERCHANT_PHONE
     *
     * @return the value of eat_merchant.MERCHANT_PHONE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getMerchantPhone() {
        return merchantPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_merchant.MERCHANT_PHONE
     *
     * @param merchantPhone the value for eat_merchant.MERCHANT_PHONE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setMerchantPhone(String merchantPhone) {
        this.merchantPhone = merchantPhone == null ? null : merchantPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_merchant.MERCHANT_ADDRESS
     *
     * @return the value of eat_merchant.MERCHANT_ADDRESS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getMerchantAddress() {
        return merchantAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_merchant.MERCHANT_ADDRESS
     *
     * @param merchantAddress the value for eat_merchant.MERCHANT_ADDRESS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setMerchantAddress(String merchantAddress) {
        this.merchantAddress = merchantAddress == null ? null : merchantAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_merchant.MERCHANT_STATUS
     *
     * @return the value of eat_merchant.MERCHANT_STATUS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getMerchantStatus() {
        return merchantStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_merchant.MERCHANT_STATUS
     *
     * @param merchantStatus the value for eat_merchant.MERCHANT_STATUS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setMerchantStatus(String merchantStatus) {
        this.merchantStatus = merchantStatus == null ? null : merchantStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_merchant.MERCHANT_EMAIL
     *
     * @return the value of eat_merchant.MERCHANT_EMAIL
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getMerchantEmail() {
        return merchantEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_merchant.MERCHANT_EMAIL
     *
     * @param merchantEmail the value for eat_merchant.MERCHANT_EMAIL
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setMerchantEmail(String merchantEmail) {
        this.merchantEmail = merchantEmail == null ? null : merchantEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_merchant.MERCHANT_NAME
     *
     * @return the value of eat_merchant.MERCHANT_NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_merchant.MERCHANT_NAME
     *
     * @param merchantName the value for eat_merchant.MERCHANT_NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_merchant.MERCHANT_SECURITY_ID
     *
     * @return the value of eat_merchant.MERCHANT_SECURITY_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Integer getMerchantSecurityId() {
        return merchantSecurityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_merchant.MERCHANT_SECURITY_ID
     *
     * @param merchantSecurityId the value for eat_merchant.MERCHANT_SECURITY_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setMerchantSecurityId(Integer merchantSecurityId) {
        this.merchantSecurityId = merchantSecurityId;
    }
}