package cn.kgc.eat.pojo;

public class EatStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_status.STATUS_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Integer statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_status.STATUS_NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String statusName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_status.STATUS_ID
     *
     * @return the value of eat_status.STATUS_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_status.STATUS_ID
     *
     * @param statusId the value for eat_status.STATUS_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_status.STATUS_NAME
     *
     * @return the value of eat_status.STATUS_NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_status.STATUS_NAME
     *
     * @param statusName the value for eat_status.STATUS_NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName == null ? null : statusName.trim();
    }
}