package cn.kgc.eat.pojo;

import java.util.Date;

public class EatSecurity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_security.SECURITY _ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Integer securityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_security.SECURITY _LV
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String securityLv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_security.SECURITY _NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String securityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_security.SECURITY _CERT_NO
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String securityCertNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_security.SECURITY _LEGAL
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String securityLegal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_security.SECURITY _ADDRESS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String securityAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_security.SECURITY _SCOPE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String securityScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_security.SECURITY _PERIOD
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Date securityPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_security.SECURITY _LICENSE_PIC
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String securityLicensePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_security.SECURITY _BUSINESS_PIC
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String securityBusinessPic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_security.SECURITY _ID
     *
     * @return the value of eat_security.SECURITY _ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Integer getSecurityId() {
        return securityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_security.SECURITY _ID
     *
     * @param securityId the value for eat_security.SECURITY _ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setSecurityId(Integer securityId) {
        this.securityId = securityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_security.SECURITY _LV
     *
     * @return the value of eat_security.SECURITY _LV
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getSecurityLv() {
        return securityLv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_security.SECURITY _LV
     *
     * @param securityLv the value for eat_security.SECURITY _LV
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setSecurityLv(String securityLv) {
        this.securityLv = securityLv == null ? null : securityLv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_security.SECURITY _NAME
     *
     * @return the value of eat_security.SECURITY _NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getSecurityName() {
        return securityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_security.SECURITY _NAME
     *
     * @param securityName the value for eat_security.SECURITY _NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setSecurityName(String securityName) {
        this.securityName = securityName == null ? null : securityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_security.SECURITY _CERT_NO
     *
     * @return the value of eat_security.SECURITY _CERT_NO
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getSecurityCertNo() {
        return securityCertNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_security.SECURITY _CERT_NO
     *
     * @param securityCertNo the value for eat_security.SECURITY _CERT_NO
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setSecurityCertNo(String securityCertNo) {
        this.securityCertNo = securityCertNo == null ? null : securityCertNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_security.SECURITY _LEGAL
     *
     * @return the value of eat_security.SECURITY _LEGAL
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getSecurityLegal() {
        return securityLegal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_security.SECURITY _LEGAL
     *
     * @param securityLegal the value for eat_security.SECURITY _LEGAL
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setSecurityLegal(String securityLegal) {
        this.securityLegal = securityLegal == null ? null : securityLegal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_security.SECURITY _ADDRESS
     *
     * @return the value of eat_security.SECURITY _ADDRESS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getSecurityAddress() {
        return securityAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_security.SECURITY _ADDRESS
     *
     * @param securityAddress the value for eat_security.SECURITY _ADDRESS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setSecurityAddress(String securityAddress) {
        this.securityAddress = securityAddress == null ? null : securityAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_security.SECURITY _SCOPE
     *
     * @return the value of eat_security.SECURITY _SCOPE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getSecurityScope() {
        return securityScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_security.SECURITY _SCOPE
     *
     * @param securityScope the value for eat_security.SECURITY _SCOPE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setSecurityScope(String securityScope) {
        this.securityScope = securityScope == null ? null : securityScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_security.SECURITY _PERIOD
     *
     * @return the value of eat_security.SECURITY _PERIOD
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Date getSecurityPeriod() {
        return securityPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_security.SECURITY _PERIOD
     *
     * @param securityPeriod the value for eat_security.SECURITY _PERIOD
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setSecurityPeriod(Date securityPeriod) {
        this.securityPeriod = securityPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_security.SECURITY _LICENSE_PIC
     *
     * @return the value of eat_security.SECURITY _LICENSE_PIC
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getSecurityLicensePic() {
        return securityLicensePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_security.SECURITY _LICENSE_PIC
     *
     * @param securityLicensePic the value for eat_security.SECURITY _LICENSE_PIC
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setSecurityLicensePic(String securityLicensePic) {
        this.securityLicensePic = securityLicensePic == null ? null : securityLicensePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_security.SECURITY _BUSINESS_PIC
     *
     * @return the value of eat_security.SECURITY _BUSINESS_PIC
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getSecurityBusinessPic() {
        return securityBusinessPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_security.SECURITY _BUSINESS_PIC
     *
     * @param securityBusinessPic the value for eat_security.SECURITY _BUSINESS_PIC
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setSecurityBusinessPic(String securityBusinessPic) {
        this.securityBusinessPic = securityBusinessPic == null ? null : securityBusinessPic.trim();
    }
}