package cn.kgc.eat.pojo;

public class EatShopping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_shopping.SHOPPING_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Long shoppingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_shopping.SHOPPING_USERID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Integer shoppingUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_shopping.SHOPPING _PRODUCTID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Long shoppingProductid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_shopping.SHOPPING _PRODUCTNAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String shoppingProductname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_shopping.SHOPPING _QUANTITY
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Long shoppingQuantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_shopping.SHOPPING_ID
     *
     * @return the value of eat_shopping.SHOPPING_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Long getShoppingId() {
        return shoppingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_shopping.SHOPPING_ID
     *
     * @param shoppingId the value for eat_shopping.SHOPPING_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setShoppingId(Long shoppingId) {
        this.shoppingId = shoppingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_shopping.SHOPPING_USERID
     *
     * @return the value of eat_shopping.SHOPPING_USERID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Integer getShoppingUserid() {
        return shoppingUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_shopping.SHOPPING_USERID
     *
     * @param shoppingUserid the value for eat_shopping.SHOPPING_USERID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setShoppingUserid(Integer shoppingUserid) {
        this.shoppingUserid = shoppingUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_shopping.SHOPPING _PRODUCTID
     *
     * @return the value of eat_shopping.SHOPPING _PRODUCTID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Long getShoppingProductid() {
        return shoppingProductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_shopping.SHOPPING _PRODUCTID
     *
     * @param shoppingProductid the value for eat_shopping.SHOPPING _PRODUCTID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setShoppingProductid(Long shoppingProductid) {
        this.shoppingProductid = shoppingProductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_shopping.SHOPPING _PRODUCTNAME
     *
     * @return the value of eat_shopping.SHOPPING _PRODUCTNAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getShoppingProductname() {
        return shoppingProductname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_shopping.SHOPPING _PRODUCTNAME
     *
     * @param shoppingProductname the value for eat_shopping.SHOPPING _PRODUCTNAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setShoppingProductname(String shoppingProductname) {
        this.shoppingProductname = shoppingProductname == null ? null : shoppingProductname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_shopping.SHOPPING _QUANTITY
     *
     * @return the value of eat_shopping.SHOPPING _QUANTITY
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Long getShoppingQuantity() {
        return shoppingQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_shopping.SHOPPING _QUANTITY
     *
     * @param shoppingQuantity the value for eat_shopping.SHOPPING _QUANTITY
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setShoppingQuantity(Long shoppingQuantity) {
        this.shoppingQuantity = shoppingQuantity;
    }
}