package cn.kgc.eat.pojo;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class EatUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_user.USER_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_user.USER_NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_user.USER_PASSWORD
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_user.USER_BORN_DATE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date userBornDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_user.USER_PHONE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_user.USER_ADDRESS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_user.USER_ADDRESS_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Integer userAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_user.USER_EMAIL
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_user.USER_GENDER
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private String userGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eat_user.USER_ROLE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    private Integer userRole;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_user.USER_ID
     *
     * @return the value of eat_user.USER_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_user.USER_ID
     *
     * @param userId the value for eat_user.USER_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_user.USER_NAME
     *
     * @return the value of eat_user.USER_NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_user.USER_NAME
     *
     * @param userName the value for eat_user.USER_NAME
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_user.USER_PASSWORD
     *
     * @return the value of eat_user.USER_PASSWORD
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_user.USER_PASSWORD
     *
     * @param userPassword the value for eat_user.USER_PASSWORD
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_user.USER_BORN_DATE
     *
     * @return the value of eat_user.USER_BORN_DATE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Date getUserBornDate() {
        return userBornDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_user.USER_BORN_DATE
     *
     * @param userBornDate the value for eat_user.USER_BORN_DATE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setUserBornDate(Date userBornDate) {
        this.userBornDate = userBornDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_user.USER_PHONE
     *
     * @return the value of eat_user.USER_PHONE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_user.USER_PHONE
     *
     * @param userPhone the value for eat_user.USER_PHONE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_user.USER_ADDRESS
     *
     * @return the value of eat_user.USER_ADDRESS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_user.USER_ADDRESS
     *
     * @param userAddress the value for eat_user.USER_ADDRESS
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_user.USER_ADDRESS_ID
     *
     * @return the value of eat_user.USER_ADDRESS_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Integer getUserAddressId() {
        return userAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_user.USER_ADDRESS_ID
     *
     * @param userAddressId the value for eat_user.USER_ADDRESS_ID
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setUserAddressId(Integer userAddressId) {
        this.userAddressId = userAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_user.USER_EMAIL
     *
     * @return the value of eat_user.USER_EMAIL
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_user.USER_EMAIL
     *
     * @param userEmail the value for eat_user.USER_EMAIL
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_user.USER_GENDER
     *
     * @return the value of eat_user.USER_GENDER
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public String getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_user.USER_GENDER
     *
     * @param userGender the value for eat_user.USER_GENDER
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setUserGender(String userGender) {
        this.userGender = userGender == null ? null : userGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eat_user.USER_ROLE
     *
     * @return the value of eat_user.USER_ROLE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public Integer getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eat_user.USER_ROLE
     *
     * @param userRole the value for eat_user.USER_ROLE
     *
     * @mbggenerated Sat Feb 22 14:23:02 CST 2020
     */
    public void setUserRole(Integer userRole) {
        this.userRole = userRole;
    }
}